isNextCallbackSetAvailable giving an error. No changes in code
Hi, I was Facing the issue using this Radius Authentication on isNextCallbackSetAvailable method, Please suggest to me why it is happening.

ERROR: isNextCallbackSetAvailable - cb 2 is of type javax.security.auth.callback.PasswordCallback
amRadiusServer:01/20/2022 10:43:06:408 PM GMT: Thread[RadiusRequestHandler-4677,5,main]: TransactionId[71841692-40ab-480e-97b0-25330b1bf4dc]
ERROR: isNextCallbackSetAvailable - cb 1 is of type javax.security.auth.callback.NameCallback
amRadiusServer:01/20/2022 10:43:06:408 PM GMT: Thread[RadiusRequestHandler-4677,5,main]: TransactionId[71841692-40ab-480e-97b0-25330b1bf4dc]
ERROR: isNextCallbackSetAvailable - cb 2 is of type javax.security.auth.callback.ConfirmationCallback